version: 0.2

phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm start
  post_build:
    commands:
      - printf '[{"name":"api-jwt","imageUri":"786661668075.dkr.ecr.us-east-1.amazonaws.com/api-jwt"}]' > imagedefinitions.json
artifacts:
  files:
    - '**/*'
